# JavaScript/TypeScript (NodeJS-v10+)
# ref: https://scrutinizer-ci.com/docs/configuration/build_reference
# spell-checker:ignore () eqeqeq
build:
  environment:
    node: v10.14.2
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run

checks:
  javascript:
    no_implicit_undefined_return: true
    no_else_return: true
    no_alert: true
    eqeqeq: true
    no_loop_var_assign: true
    no_param_assign: true
    no_var: true

filter:
  dependency_paths:
    - 'node_modules/'
  excluded_paths:
    - 'dist/'
    - 'src/types/'
    - 'test/'
    - 'vendor/'
    - '*.spec.js'
    - '*.spec.ts'
    - '*.test.js'
    - '*.test.ts'
