language: node_js
os:
  - linux
  - osx
node_js:
  - '18'
  - '16'
  - '14' # #maint: [2021-02-19; rivy] `npm install` suddenly fails to correctly install 'npm-run-all'; disabled awaiting TravisCI fix
  - '12'
  - '10'
after_success:
  - npm run coverage
